### ISSUE TITLE
No wiki/ no crafting?

### ISSUE THREAD

**Issue by NikitaIsNext** [Yirmiri/Excessive-Building#10]
I don't know if I'm just really stupid, but I can't find the wiki on the github ANYWHERE and if I e.g. use cherry planks to make a cherry crafting table, then it just gives me "Crafting Table/ Oak Crafting Table". Idk what I'm doing wrong or where the wiki is

**Comment by Yirmiri** [comment]
I will look into this, using 4 planks of cherry should output a cherry crafting table. Also currently there is no updated wiki :P
What game version, mod loader, and mod version are you using?

**Comment by NikitaIsNext** [comment]
Game version: 1.21.1, mod loader: Fabric, Mod Version: Prism Launcher says 3.3.2

Maybe it's because I didn't create a new world but opened one I played on before? Idk

Also, if there is no wiki, how is somebody uhh, supposed to know how to create the new blocks xD ?

**Comment by Yirmiri** [comment]
Thank you for the information I'll fix this soon !!
And for the wiki- since I do everything on my own + having my own life I don't really have the time to constantly maintain a wiki especially one with information on exact recipes and stuffs so if you are wanting to find recipes in the mod I'd recommend using either the JEI or EMI mods (they let you view how to craft items and automatically work with most recipes)

**Comment by NikitaIsNext** [comment]
No problem, I was just INCREDIBLY confused because on the mod page it said „Wiki here:“ so I thought I‘m incredibly stupid for not finding it.

**Comment by Yirmiri** [comment]
Ah must have been a remnant of when I did have a wiki (though I didn't maintain it well so I took it down)
Anyways I have fixed the issue and it will be available in the next version (v3.3.3) which should be up soon (hopefully)
